"""Install the RapidCADPy auto-start connector into FreeCAD's user modules."""

from __future__ import annotations

import argparse
import os
import shutil
import sys
from pathlib import Path
from typing import Any, Dict, Optional

_GENERATED_MARKER = "# Generated by RapidCADPy FreeCAD connector installer."


def discover_freecad_user_mod_dir() -> Path:
    """Locate FreeCAD's per-user ``Mod`` directory."""
    configured = os.environ.get("RAPIDCADPY_FREECAD_USER_MOD_DIR", "").strip()
    if configured:
        return Path(configured).expanduser().resolve()

    try:
        from .app import ensure_freecad_python_path

        ensure_freecad_python_path()
        import FreeCAD

        user_data = str(FreeCAD.ConfigGet("UserAppData") or "").strip()
        if user_data:
            return (Path(user_data).expanduser().resolve() / "Mod").resolve()
    except Exception:
        pass

    home = Path.home()
    if sys.platform == "darwin":
        return (home / "Library" / "Application Support" / "FreeCAD" / "Mod").resolve()
    if os.name == "nt":
        app_data = os.environ.get("APPDATA", "").strip()
        base = Path(app_data).expanduser() if app_data else home / "AppData" / "Roaming"
        return (base / "FreeCAD" / "Mod").resolve()
    xdg_data_home = os.environ.get("XDG_DATA_HOME", "").strip()
    base = (
        Path(xdg_data_home).expanduser() if xdg_data_home else home / ".local" / "share"
    )
    return (base / "FreeCAD" / "Mod").resolve()


def _init_gui_source(package_root: Path) -> str:
    return f'''{_GENERATED_MARKER}
"""Start the RapidCADPy bridge whenever the FreeCAD GUI starts."""

import sys

import FreeCAD

_RAPIDCADPY_PACKAGE_ROOT = {str(package_root)!r}

try:
    from PySide import QtCore
except ImportError:
    from PySide2 import QtCore


def _start_rapidcadpy_connector():
    try:
        # FreeCAD restores parts of sys.path after executing addon init files,
        # so insert the package root again in the deferred GUI callback.
        if _RAPIDCADPY_PACKAGE_ROOT not in sys.path:
            sys.path.insert(0, _RAPIDCADPY_PACKAGE_ROOT)

        # Some FreeCAD builds wrap imports through Shiboken and do not honor a
        # path inserted by a deferred callback. Seed the package explicitly;
        # its normal submodule imports then use this package search location.
        if "rapidcadpy" not in sys.modules:
            import importlib.util
            import os

            package_dir = os.path.join(_RAPIDCADPY_PACKAGE_ROOT, "rapidcadpy")
            package_spec = importlib.util.spec_from_file_location(
                "rapidcadpy",
                os.path.join(package_dir, "__init__.py"),
                submodule_search_locations=[package_dir],
            )
            package_module = importlib.util.module_from_spec(package_spec)
            sys.modules["rapidcadpy"] = package_module
            package_spec.loader.exec_module(package_module)

        from rapidcadpy.integrations.freecad.gui_bridge import (
            start_persistent_bridge,
        )

        result = start_persistent_bridge()
        FreeCAD.Console.PrintMessage(
            "RapidCADPy connector ready: {{}}\\n".format(
                result.get("instance_id", "unknown")
            )
        )
    except Exception:
        import traceback

        FreeCAD.Console.PrintError(
            "RapidCADPy connector failed to start:\\n{{}}\\n".format(
                traceback.format_exc()
            )
        )


QtCore.QTimer.singleShot(0, _start_rapidcadpy_connector)
'''


def install_freecad_connector(
    mod_dir: Optional[str] = None,
    package_root: Optional[str] = None,
) -> Dict[str, Any]:
    """Install an auto-start module that imports the current RapidCADPy package."""
    resolved_mod_dir = (
        Path(mod_dir).expanduser().resolve()
        if mod_dir
        else discover_freecad_user_mod_dir()
    )
    source_package_root = (
        Path(package_root).expanduser().resolve()
        if package_root
        else Path(__file__).resolve().parents[3]
    )
    if not (source_package_root / "rapidcadpy").is_dir():
        raise ValueError(f"RapidCADPy package root not found: {source_package_root}")

    addon_dir = resolved_mod_dir / "RapidCADConnector"
    init_gui_path = addon_dir / "InitGui.py"
    if init_gui_path.exists():
        existing = init_gui_path.read_text(encoding="utf-8")
        if _GENERATED_MARKER not in existing:
            raise FileExistsError(
                "Refusing to overwrite an unmanaged FreeCAD addon at " f"{addon_dir}"
            )

    addon_dir.mkdir(parents=True, exist_ok=True)
    installed_package_root = addon_dir / "_vendor"
    installed_package_dir = installed_package_root / "rapidcadpy"
    if installed_package_dir.is_dir():
        shutil.rmtree(installed_package_dir)
    shutil.copytree(
        source_package_root / "rapidcadpy",
        installed_package_dir,
        ignore=shutil.ignore_patterns(
            "__pycache__",
            "*.pyc",
            "*.pyo",
            ".pytest_cache",
        ),
    )
    init_gui_path.write_text(
        _init_gui_source(installed_package_root),
        encoding="utf-8",
    )
    (addon_dir / "Init.py").write_text(
        f"{_GENERATED_MARKER}\n",
        encoding="utf-8",
    )
    namespace_module = addon_dir / "freecad" / "rapidcad_connector"
    namespace_module.mkdir(parents=True, exist_ok=True)
    (namespace_module / "__init__.py").write_text(
        f"{_GENERATED_MARKER}\n",
        encoding="utf-8",
    )
    (namespace_module / "init.py").write_text(
        f"{_GENERATED_MARKER}\n",
        encoding="utf-8",
    )
    (namespace_module / "init_gui.py").write_text(
        _init_gui_source(installed_package_root),
        encoding="utf-8",
    )
    (addon_dir / "package.xml").write_text(
        """<?xml version="1.0" encoding="UTF-8"?>
<package format="1">
  <name>RapidCAD Connector</name>
  <description>Starts the local RapidCADPy bridge for external application control.</description>
  <version>0.1.0</version>
  <maintainer email="">RapidCADPy</maintainer>
  <license file="">MIT</license>
</package>
""",
        encoding="utf-8",
    )
    return {
        "ok": True,
        "summary": "Installed the RapidCADPy connector for FreeCAD",
        "addon_dir": str(addon_dir),
        "package_root": str(installed_package_root),
        "source_package_root": str(source_package_root),
        "restart_required": True,
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Install the RapidCADPy connector into FreeCAD."
    )
    parser.add_argument("--mod-dir", default=None)
    parser.add_argument("--package-root", default=None)
    arguments = parser.parse_args()
    result = install_freecad_connector(
        mod_dir=arguments.mod_dir,
        package_root=arguments.package_root,
    )
    print(result["summary"])
    print(f"Addon: {result['addon_dir']}")
    print("Restart FreeCAD once to activate it.")


if __name__ == "__main__":
    main()
