// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "api/mesher-base-example.mdx": () => import("../content/docs/api/mesher-base-example.mdx?collection=docs"), "computer-aided-design/built-in-profiles.mdx": () => import("../content/docs/computer-aided-design/built-in-profiles.mdx?collection=docs"), "computer-aided-design/fluent-api.mdx": () => import("../content/docs/computer-aided-design/fluent-api.mdx?collection=docs"), "computer-aided-design/index.mdx": () => import("../content/docs/computer-aided-design/index.mdx?collection=docs"), "computer-aided-design/overview.mdx": () => import("../content/docs/computer-aided-design/overview.mdx?collection=docs"), "computer-aided-design/shape.mdx": () => import("../content/docs/computer-aided-design/shape.mdx?collection=docs"), "computer-aided-design/sweep.mdx": () => import("../content/docs/computer-aided-design/sweep.mdx?collection=docs"), "computer-aided-design/workplanes.mdx": () => import("../content/docs/computer-aided-design/workplanes.mdx?collection=docs"), "advanced/2d-exports.mdx": () => import("../content/docs/advanced/2d-exports.mdx?collection=docs"), "advanced/3d-exports.mdx": () => import("../content/docs/advanced/3d-exports.mdx?collection=docs"), "advanced/inventor-reverse-engineer.mdx": () => import("../content/docs/advanced/inventor-reverse-engineer.mdx?collection=docs"), "advanced/visualizations.mdx": () => import("../content/docs/advanced/visualizations.mdx?collection=docs"), "finite-element-analysis/constraints.mdx": () => import("../content/docs/finite-element-analysis/constraints.mdx?collection=docs"), "finite-element-analysis/fea-analysis.mdx": () => import("../content/docs/finite-element-analysis/fea-analysis.mdx?collection=docs"), "finite-element-analysis/loads.mdx": () => import("../content/docs/finite-element-analysis/loads.mdx?collection=docs"), "finite-element-analysis/materials.mdx": () => import("../content/docs/finite-element-analysis/materials.mdx?collection=docs"), "finite-element-analysis/optimization.mdx": () => import("../content/docs/finite-element-analysis/optimization.mdx?collection=docs"), "finite-element-analysis/visualization.mdx": () => import("../content/docs/finite-element-analysis/visualization.mdx?collection=docs"), }),
};
export default browserCollections;