// @ts-nocheck -- skip type checking
import * as docs_9 from "../content/docs/analysis/fea-analysis.mdx?collection=docs&hash=1756974978816"
import * as docs_8 from "../content/docs/advanced/visualizations.mdx?collection=docs&hash=1756974978816"
import * as docs_7 from "../content/docs/advanced/inventor-reverse-engineer.mdx?collection=docs&hash=1756974978816"
import * as docs_6 from "../content/docs/advanced/3d-exports.mdx?collection=docs&hash=1756974978816"
import * as docs_5 from "../content/docs/advanced/2d-exports.mdx?collection=docs&hash=1756974978816"
import * as docs_4 from "../content/docs/get-started/workplanes.mdx?collection=docs&hash=1756974978816"
import * as docs_3 from "../content/docs/get-started/overview.mdx?collection=docs&hash=1756974978816"
import * as docs_2 from "../content/docs/get-started/index.mdx?collection=docs&hash=1756974978816"
import * as docs_1 from "../content/docs/get-started/fluent-api.mdx?collection=docs&hash=1756974978816"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1756974978816"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","absolutePath":"/Users/elias.berger/rapidcadpy/docs/content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"get-started/fluent-api.mdx","absolutePath":"/Users/elias.berger/rapidcadpy/docs/content/docs/get-started/fluent-api.mdx"}, data: docs_1 }, { info: {"path":"get-started/index.mdx","absolutePath":"/Users/elias.berger/rapidcadpy/docs/content/docs/get-started/index.mdx"}, data: docs_2 }, { info: {"path":"get-started/overview.mdx","absolutePath":"/Users/elias.berger/rapidcadpy/docs/content/docs/get-started/overview.mdx"}, data: docs_3 }, { info: {"path":"get-started/workplanes.mdx","absolutePath":"/Users/elias.berger/rapidcadpy/docs/content/docs/get-started/workplanes.mdx"}, data: docs_4 }, { info: {"path":"advanced/2d-exports.mdx","absolutePath":"/Users/elias.berger/rapidcadpy/docs/content/docs/advanced/2d-exports.mdx"}, data: docs_5 }, { info: {"path":"advanced/3d-exports.mdx","absolutePath":"/Users/elias.berger/rapidcadpy/docs/content/docs/advanced/3d-exports.mdx"}, data: docs_6 }, { info: {"path":"advanced/inventor-reverse-engineer.mdx","absolutePath":"/Users/elias.berger/rapidcadpy/docs/content/docs/advanced/inventor-reverse-engineer.mdx"}, data: docs_7 }, { info: {"path":"advanced/visualizations.mdx","absolutePath":"/Users/elias.berger/rapidcadpy/docs/content/docs/advanced/visualizations.mdx"}, data: docs_8 }, { info: {"path":"analysis/fea-analysis.mdx","absolutePath":"/Users/elias.berger/rapidcadpy/docs/content/docs/analysis/fea-analysis.mdx"}, data: docs_9 }], [{"info":{"path":"meta.json","absolutePath":"/Users/elias.berger/rapidcadpy/docs/content/docs/meta.json"},"data":{"title":"Documentation","pages":["index","get-started","analysis","advanced"]}}, {"info":{"path":"advanced/meta.json","absolutePath":"/Users/elias.berger/rapidcadpy/docs/content/docs/advanced/meta.json"},"data":{"title":"Advanced","pages":["2d-exports","3d-exports","visualizations","inventor-reverse-engineer"]}}, {"info":{"path":"get-started/meta.json","absolutePath":"/Users/elias.berger/rapidcadpy/docs/content/docs/get-started/meta.json"},"data":{"title":"Get Started","pages":["index","overview","workplanes","fluent-api"]}}, {"info":{"path":"analysis/meta.json","absolutePath":"/Users/elias.berger/rapidcadpy/docs/content/docs/analysis/meta.json"},"data":{"title":"Analysis","pages":["fea-analysis"]}}])